# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='degree',
            field=models.CharField(choices=[('B', 'Bachelor'), ('M', 'Master'), ('D', 'Doctor')], default='your_degree', max_length=2),
        ),
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(default='your_name', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
