# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='member',
            table='message_member',
        ),
        migrations.AlterModelTable(
            name='message',
            table='message_message',
        ),
    ]
