# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20170119_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auther',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auther', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='degree',
            field=models.CharField(choices=[('B', 'Bachelor'), ('M', 'Master'), ('D', 'Doctor')], default='your_degree', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='year',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='auther',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='message.Auther'),
            preserve_default=False,
        ),
    ]
