# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20170122_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='year',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=0, max_length=20),
        ),
    ]
