# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_auto_20170122_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='auther',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Auther',
        ),
    ]
