# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_auto_20170122_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='degree',
        ),
    ]
