# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_remove_message_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='year',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
