# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_auto_20170122_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='auther',
        ),
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(default='your_name', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='message_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_member', to='message.Message', to_field='name'),
        ),
        migrations.AddField(
            model_name='member',
            name='message_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_member', to='message.Message', to_field='author'),
        ),
        migrations.AddField(
            model_name='member',
            name='messages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='message.Message', to_field='message'),
        ),
    ]
