# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_auto_20170122_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='message_by',
        ),
        migrations.RemoveField(
            model_name='member',
            name='message_to',
        ),
        migrations.RemoveField(
            model_name='member',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='message',
            name='name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='year',
        ),
        migrations.AddField(
            model_name='member',
            name='message2u',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='message.Message', to_field='message'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(default='your_name', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='year',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='message_for',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='message.Member', to_field='name'),
            preserve_default=False,
        ),
    ]
