# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0009_auto_20170123_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='message_from',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='message.Message', to_field='author'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='message2u',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_to_you', to='message.Message', to_field='message'),
        ),
    ]
