# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0010_auto_20170123_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='message_from',
        ),
        migrations.AlterField(
            model_name='member',
            name='message2u',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.Message'),
        ),
    ]
