# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0011_auto_20170123_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message_for',
            new_name='message2',
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer', to='message.Member', to_field='name'),
        ),
    ]
