# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0013_remove_member_message2u'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message2',
        ),
        migrations.AddField(
            model_name='message',
            name='created_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='message.Member', to_field='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='message.Member', to_field='name'),
        ),
    ]
