# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0014_auto_20170123_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='created_by',
        ),
        migrations.AddField(
            model_name='message',
            name='create_for',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='create_for', to='message.Member', to_field='name'),
            preserve_default=False,
        ),
    ]
